### PR TITLE
Add details on managing tombstones (#686)

### PR DESCRIPTION
**Pull request by JFlath**

### CODE REVIEW

**Comment by JFlath** [comment]
I'm sure there's a clever way of linking it back to the issue, but I've just spent far too long confused because the PR number and the Issue number are 1 away from each other, so I'll leave it to you ;).

**Comment by JFlath** [comment]
Doh! Relative links - will try to get to that.

**Comment by jamiltz** [comment]
i'll sort out the relative links! That changes is really great, reviewing now.

**Comment by JFlath** [comment]
You just want to get your commit count up don't you ;)? Thanks very much :)

**Comment by jamiltz** [comment]
Actually tried to maximize my line counts with a file move but github didn't count it :(
The change looks good, merged!

**Comment by jamiltz** [comment]
and deployed the 1.4 docs. kinda stuck deploying the 1.3 ones atm but will be online soon.

**Pull request merged**
