### PR TITLE
fix https://github.com/couchbaselabs/mobile-training-todo/issues/76

### PR DESCRIPTION
**Pull request by jamiltz**

### CODE REVIEW

**Comment by jamiltz** [comment]
@raghusarangapani the updated project should fix the error message when importing the project in Android Studio. Can you try downloading it from the new URL and see if it still shows up?

**Comment by raghusarangapani** [comment]
I verified that the new link https://cl.ly/1K2l2E1f001B/project.zip proposed in this change md-docs/_config.yml does not have this error. But the website still points to the old link https://cl.ly/1Y3W3s2e1D0y/project.zip at https://developer.couchbase.com/documentation/mobile/1.4/training/develop/create-database/index.html

**Comment by jamiltz** [comment]
Ok thanks for verifying the fix! Can you merge to master? Will deploy to the website afterwards.

**Comment by raghusarangapani** [comment]
Done

**Comment by jamiltz** [comment]
updated on web page.

**Pull request merged**
