### PR TITLE
Update common.yaml

### PR DESCRIPTION
**Pull request by adamcfraser**
Add note about session handling when the password is specified on a user update via the admin API.

### CODE REVIEW

**Comment by adamcfraser** [comment]
@jamiltz Seth hit this scenario and thought it should be documented.

Not sure whether this PR should target master or dev - let me know if I should move it.

**Comment by jamiltz** [comment]
Yes it should go in master since it doesn't relate to new features or a new doc page like the FAQ for example.

**Comment by jamiltz** [comment]
I may have merged this too early. The user parameters modified in this PR is used on the `PUT, POST /{db}/_user` endpoint. But I understand that it would occur only on the `/{db}/_session` endpoint when specifying a password over the Admin API? If so I think it should be document [here](https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/swagger/paths/sg/admin.yaml#L424).

**Comment by adamcfraser** [comment]
This PR *is* intended to modify the description of the 'password' parameter for the PUT/POST `db/_user`.  The intention is to clarify that if the user password gets changed through the _user API, any active sessions for that user will be invalidated.

**Comment by jamiltz** [comment]
Ok now I get it! FYI moved the [user param](https://github.com/couchbaselabs/couchbase-mobile-portal/commit/0c978595b7834efbc0667771365edf6b646e2483) from `common.yaml` to `sg.yaml` since it only applies to SG.

**Pull request merged**
