### PR TITLE
Fixes #750 Add docs for SG _revtree admin endpoint

### LINKED ISSUE #750: Add docs for SG _revtree admin endpoint
See https://github.com/couchbase/sync_gateway/pull/2670#issuecomment-310520623 for example usage

### PR DESCRIPTION
**Pull request by tleyden**
First stab at adding docs for `_revtree` endpoint (not merged yet -- see https://github.com/couchbase/sync_gateway/pull/2670)

What should "description" be?  How can I add an example response?  Here's what the response looks like:

```
< HTTP/1.1 200 OK
< Content-Length: 97
< Content-Type: text/plain charset=utf-8
< Server: /1.5 branch/ commit/
< Date: Thu, 22 Jun 2017 22:30:30 GMT
<
* Connection #0 to host localhost left intact
digraph graphname{"1-ecbd22495c41163e3657699fd1f5ca28" -> "2-9751b0b11d5cbeae6d9d756603b4cdc2"; }
```

### CODE REVIEW

**Comment by jamiltz** [comment]
@tleyden I'm not sure how to describe a response object that isn't JSON.

Maybe the description can have the following instructions:

- which software to use to convert it to a diagram?
- how to install it?
- what command to run to convert the response into a diagram?

**Comment by tleyden** [comment]
@jamiltz I added a new commit that should address that

**Comment by jamiltz** [comment]
@tleyden I tried `brew install dot` which didn't work. But `brew install graphviz` did. Also made a few other minor changes. Merging. Feel free to comment if this needs further attention.

**Comment by tleyden** [comment]
@jamiltz awesome, thanks!  LGTM

**Pull request merged**
