### PR TITLE
Update the running replications intro

### PR DESCRIPTION
**Pull request by jamiltz**
Connects to #405

### CODE REVIEW

**Comment by jamiltz** [comment]
@HodGreeley can you review and let me know if that sounds like a better intro.

@tleyden can review that change for correctness (I'm not sure if the diagram is correct/needed).

**Comment by tleyden** [comment]
The diagram looks good!

This is a bit confusing to me though ..

> On the architecture diagram below, each data centre can perform write and read operations.

It's confusing since a date center isn't performing the read/write operations.

What about saying "any changes that users/systems make on either Sync Gateway instance will be replicated to the other Sync Gateway instance"

**Comment by jamiltz** [comment]
Yes agreed. Was trying to highlight the fact write operations can happen on either. Your suggestion makes it clearer and also covers that point.

Can you make that change?

**Comment by tleyden** [comment]
Usually the PR submitter makes these kind of changes.  Unless you have a specific reason for me to make the change ..

**Comment by jamiltz** [comment]
Noted. Thanks!

**Comment by tleyden** [comment]
Btw `377-docs-1.3` is kind of a strange name for a branch .. whats the 377 mean?

**Comment by jamiltz** [comment]
The issue number. It's so it connects to the issue on waffle and moves it to in progress automatically https://github.com/waffleio/waffle.io/wiki/FAQs#automatically-move-issues-in-progress

**Pull request merged**
