### PR TITLE
1.3 Dev Preview docs

### PR DESCRIPTION
**Pull request by jamiltz**
[WIP]

Todo:
- [ ] Add the docs for the CBL side and the code snippet in each language.
- [ ] OpenID Connect in Grocery Sync Android (https://github.com/couchbase/couchbase-lite-java-core/issues/1274#issuecomment-230044605)
- [x] Complete the providers table of properties and their meaning.
- [ ] As a first time reader and new to Open ID Connect I don't know where to find the client ID or validation key for the google auth provider for example. As discussed on the call, the guide should include a step by step guide in an actual app (possibly ToDoLite iOS or Grocery Sync iOS).
- [ ] Paragraph that explains how a google auth user translates as a Sync Gateway user and is interpreted in the sync gateway.
- [ ] TTL on SG REST API
- [x] Diagram for OpenID Connect
- [ ] TTL on CBL REST API
- [ ] OpenIDConnect, have a part that goes into the auth code flow. And then the additional params if needed. For each param, there's a use case that we should go more into. Have instructions for the straightforward case, and then for the more complex ones.

Todo for today:
- [x] Twitter doesn't support OpenID, we've tested with azure, paypal, yahoo, active directory
- [x] Add link to github todolite ios branch
- [x] Download links

Staging: http://developer-stage.cbauthx.com/documentation/mobile/1.2/developer-preview/download/index.html

Connects to #343

### CODE REVIEW

**Comment by jamiltz** [comment]
@adamcfraser I've updated the content with minor changes per our discussion today.

Here's the plan:

1. Quick review of the DP docs, we know some content is missing and can add and refine during the DP.
2. Share the link to the GitHub release notes for SG and iOS (cc @snej).
3. Merge this PR. The uncompleted todos in the first comment of the PR will go in a new issue.
4. Deploy to site (tomorrow).
5. Share the link in ggroups and forum (tomorrow).

The preview currently is at http://developer-stage.cbauthx.com/documentation/mobile/1.2/developer-preview/download/index.html.

**Comment by snej** [comment]
iOS/Mac/tvOS release notes are live at https://github.com/couchbase/couchbase-lite-ios/releases/tag/1.3

**Comment by snej** [comment]
Jim got the .NET release notes up at https://github.com/couchbase/couchbase-lite-net/releases/tag/1.3

**Comment by snej** [comment]
Java/Android release notes (still in draft form, so not publicly visible yet):
https://github.com/couchbase/couchbase-lite-java-core/releases/
https://github.com/couchbase/couchbase-lite-android/releases/
https://github.com/couchbase/couchbase-lite-java/releases/

**Pull request merged**
