### PR TITLE
Fix _replicate

### PR DESCRIPTION
**Pull request by jamiltz**
There is no replication_id parameter in the request body of _replicate on CBL

@snej How is a replication stopped via the REST API? What else should be sent with the `cancel: true` property?

Connects #372

### CODE REVIEW

**Comment by snej** [comment]
You can look at the [CouchDB docs](http://docs.couchdb.org/en/latest/api/server/common.html#replicate) for comparison.

>"You can cancel continuous replication by adding the cancel field to the JSON request object and setting the value to true. Note that the structure of the request must be identical to the original for the cancellation request to be honoured. For example, if you requested continuous replication, the cancellation request must also contain the continuous field."

The CouchDB docs don't mention a `replication_id` parameter, so I wonder where the one in our docs came from...

**Comment by ajres** [comment]
[replication_id is available in couchDB 1.2 and later](https://wiki.apache.org/couchdb/Replication#New_features_introduced_in_CouchDB_1.2.0)

Sync Gateway _replicate endpoint supports cancellation by matching source/target/continuous or by using replication_id.

**Comment by jamiltz** [comment]
From me https://github.com/couchbaselabs/couchbase-mobile-portal/commit/947ae6bb830c70c4152ff0bf39a2542a4371b773#diff-32c5c95d3cc5c36859ea9d737d00f821

There is a `replication_id` parameter in the response of `_active_tasks` so it's not completely out of this world but a mistake nonetheless. I will make sure to ask for reviews more frequently.

**Comment by jamiltz** [comment]
@ajres Oh, it is there on the /_replicate endpoint.

**Comment by jamiltz** [comment]
So I will remove it in the case of the CBL REST API only.

**Pull request merged**
