### PR TITLE
Fix documentation error - this config file only works for older versions

### PR DESCRIPTION
**Pull request by CrazyPython**

### CODE REVIEW

**Comment by tleyden** [comment]
I just checked, and this PR matches what is in https://github.com/couchbase/sync_gateway/blob/master/examples/openid-connect.json

Thanks @CrazyPython!

**Comment by tleyden** [comment]
I reverted this and opened a new issue in the Sync Gateway repo here: https://github.com/couchbase/sync_gateway/issues/2996

**Comment by tleyden** [comment]
@CrazyPython what older versions were you referring to?  Older versions of google openid connect, or older versions of SG?  

Any details you can provide about what didn't work would be useful.

**Comment by jamiltz** [comment]
FWIW, the [How-to guide](https://developer.couchbase.com/documentation/mobile/1.4/guides/authentication/openid/google/index.html#setting-up-sync-gateway) uses a `callback_url` in the config. The absence of `callback_url` in the config discussed here could be a reason although it's mentioned as being optional on the [props page](https://developer.couchbase.com/documentation/mobile/1.4/guides/authentication/openid/configuration-options/index.html).

**Comment by CrazyPython** [comment]
@tleyden I assumed it didn't work with an older version because copy-pasting from different docs gave me working code.

**Pull request merged**
