### PR TITLE
Add missing parameters to attachment put method

### PR DESCRIPTION
**Pull request by jdupouy**
This adds some missing parameters (rev and body) for the attachment path.

### CODE REVIEW

**Comment by jamiltz** [comment]
👍

**Comment by jamiltz** [comment]
@jdupouy can you explain how you got this endpoint to work with the change to the spec? I'm trying to use it to upload an image from the browser to SG but no luck so far.

**Comment by jdupouy** [comment]
I use it in a nodejs application with the swagger-client library. I doubt that swagger-client is reading the type of the parameters so I didn't get into trouble. I was just missing the parameters at that time, as they were not declared the client wasn't sending them at all.

Retrospectively, now that I am using a little bite the Java generated code I think the following body declaration of the request would be better:
```
parameter:
  name: binary
  in: body
  description: Raw data request body
  schema:
    type: string
    format: binary 
```

**Comment by jamiltz** [comment]
I came to the same conclusion about using `formart: binary`. Can you share the swagger client code snippet you have to upload the attachment as a string binary? Also talking about this on https://github.com/couchbaselabs/couchbase-mobile-portal/issues/536#issuecomment-285469402

**Comment by jdupouy** [comment]
Here below you will find a working exemple for swagger client.

```
const Swagger = require('swagger-client');
const adminSpec = require('../files/swagger/admin.json');

adminSpec.host = config.sync_gateway.admin_host;

var db = 'database';
var doc = 'averyuniqueid';
var attachment = 'myattachment';
var body = 'A very unique body';

new Swagger({
	spec: adminSpec,
	usePromise: true
}).then(function (client) {
	return client.document.put_db_doc({
		db: db,
		doc: doc,
		Document: {
			name: "A very unique Name"
		}
	}).then(function (success) {
		console.log(success);
		return success.obj.rev;
	}).then(function (rev) {
		return client.attachment.put_db_doc_attachment({
			db: db,
			doc: doc,
			attachment: attachment,
			body: body,
			rev: rev
		}, {
			requestContentType: 'application/text'
		}).then(function (success) {
			console.log(success);
			return success.obj.rev;
		})
	}).then(function (rev) {
		return client.attachment.get_db_doc_attachment({
			db: db,
			doc: doc,
			rev: rev,
			attachment: attachment
		}).then(function (result) {
			console.log(result.data);
			return rev;
		})
	}).then(function (rev) {
		return client.document.delete_db_doc({
			db: db,
			doc: doc,
			rev: rev
		}).then(function (success) {
			console.log(success)
		})
	}).catch(function (err) {
		console.log(err)
	})
});
```

**Comment by jamiltz** [comment]
Thanks, that confirms that the `put_db_doc_attachment` method works with the change from this PR. The next challenge is to make it work for any content types like `application/pdf`, `image/png`. I think the file has to be converted to a binary string and then passed in the body for it to work.

**Comment by jdupouy** [comment]
If you are dealing with the the swagger-client I had a some troubles myself to put attachments, especially with [this part](https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L266). I proposed this [PR](https://github.com/swagger-api/swagger-js/pull/959) a few days ago tu deal with Buffers.

**Pull request merged**
